export const validUser = {
  username: 'Login',
  role: 'admin',
  email: 'loginTest@test.com',
  password: 'testandoLogin',
};

export const validUserLogin = {
  email: 'loginTest@test.com',
  password: 'testandoLogin'
};

export const teamList: any = [ // : {id: number, team_name: string}[]
  { id: 1, team_name: 'Avaí/Kindermann' },
  { id: 2, team_name: 'Bahia' },
  { id: 3, team_name: 'Botafogo' },
  { id: 4, team_name: 'Corinthians' },
  { id: 5, team_name: 'Cruzeiro' },
  { id: 6, team_name: 'Ferroviária' },
  { id: 7, team_name: 'Flamengo' },
  { id: 8, team_name: 'Grêmio' },
  { id: 9, team_name: 'Internacional' },
  { id: 10, team_name: 'Minas Brasília' },
  { id: 11, team_name: 'Napoli-SC' },
  { id: 12, team_name: 'Palmeiras' },
  { id: 13, team_name: 'Real Brasília' },
  { id: 14, team_name: 'Santos' },
  { id: 15, team_name: 'São José-SP' },
  { id: 16, team_name: 'São Paulo' },
];

export const matchesFinishedList: any = [
  { home_team: 16, home_team_goals: 1, away_team: 8, away_team_goals: 1, in_progress: false }, 
  { home_team: 9, home_team_goals: 1, away_team: 14, away_team_goals: 1, in_progress: false },
  { home_team: 4, home_team_goals: 3, away_team: 11, away_team_goals: 0, in_progress: false },
  { home_team: 3, home_team_goals: 0, away_team: 2, away_team_goals: 0, in_progress: false },
  { home_team: 7, home_team_goals: 1, away_team: 10, away_team_goals: 1, in_progress: false },
  { home_team: 5, home_team_goals: 1, away_team: 13, away_team_goals: 1, in_progress: false },
  { home_team: 12, home_team_goals: 2, away_team: 6, away_team_goals: 2, in_progress: false },
  { home_team: 15, home_team_goals: 0, away_team: 1, away_team_goals: 1, in_progress: false },
  { home_team: 1, home_team_goals: 0, away_team: 12, away_team_goals: 3, in_progress: false },
  { home_team: 2, home_team_goals: 0, away_team: 9, away_team_goals: 2, in_progress: false },
  { home_team: 13, home_team_goals: 1, away_team: 3, away_team_goals: 0, in_progress: false },
  { home_team: 6, home_team_goals: 0, away_team: 4, away_team_goals: 1, in_progress: false },
  { home_team: 8, home_team_goals: 2, away_team: 5, away_team_goals: 1, in_progress: false },
  { home_team: 14, home_team_goals: 2, away_team: 16, away_team_goals: 1, in_progress: false },
  { home_team: 10, home_team_goals: 0, away_team: 15, away_team_goals: 1, in_progress: false },
  { home_team: 11, home_team_goals: 0, away_team: 7, away_team_goals: 0, in_progress: false },
  { home_team: 1, home_team_goals: 2, away_team: 8, away_team_goals: 3, in_progress: false },
  { home_team: 12, home_team_goals: 4, away_team: 5, away_team_goals: 2, in_progress: false },
  { home_team: 11, home_team_goals: 2, away_team: 2, away_team_goals: 2, in_progress: false },
  { home_team: 7, home_team_goals: 0, away_team: 9, away_team_goals: 1, in_progress: false },
];

export const matchesInProgressList: any = [
  { home_team: 16, home_team_goals: 2, away_team: 9, away_team_goals: 0, in_progress: true },
  { home_team: 6, home_team_goals: 1, away_team: 1, away_team_goals: 0, in_progress: true },
  { home_team: 11, home_team_goals: 0, away_team: 10, away_team_goals: 0, in_progress: true },
  { home_team: 7, home_team_goals: 2, away_team: 15, away_team_goals: 2, in_progress: true },
  { home_team: 5, home_team_goals: 1, away_team: 3, away_team_goals: 1, in_progress: true },
  { home_team: 4, home_team_goals: 1, away_team: 12, away_team_goals: 1, in_progress: true },
  { home_team: 8, home_team_goals: 1, away_team: 14, away_team_goals: 2, in_progress: true },
  { home_team: 13, home_team_goals: 1, away_team: 2, away_team_goals: 1, in_progress: true },
];

export const matchesList: any = [
  { id: 1, home_team: 16, home_team_goals: 1, away_team: 8, away_team_goals: 1, in_progress: false }, 
  { id: 2, home_team: 9, home_team_goals: 1, away_team: 14, away_team_goals: 1, in_progress: false },
  { id: 3, home_team: 4, home_team_goals: 3, away_team: 11, away_team_goals: 0, in_progress: false },
  { id: 4, home_team: 3, home_team_goals: 0, away_team: 2, away_team_goals: 0, in_progress: false },
  { id: 5, home_team: 7, home_team_goals: 1, away_team: 10, away_team_goals: 1, in_progress: false },
  { id: 6, home_team: 5, home_team_goals: 1, away_team: 13, away_team_goals: 1, in_progress: false },
  { id: 7, home_team: 12, home_team_goals: 2, away_team: 6, away_team_goals: 2, in_progress: false },
  { id: 8, home_team: 15, home_team_goals: 0, away_team: 1, away_team_goals: 1, in_progress: false },
  { id: 9, home_team: 1, home_team_goals: 0, away_team: 12, away_team_goals: 3, in_progress: false },
  { id: 10, home_team: 2, home_team_goals: 0, away_team: 9, away_team_goals: 2, in_progress: false },
  { id: 11, home_team: 13, home_team_goals: 1, away_team: 3, away_team_goals: 0, in_progress: false },
  { id: 12, home_team: 6, home_team_goals: 0, away_team: 4, away_team_goals: 1, in_progress: false },
  { id: 13, home_team: 8, home_team_goals: 2, away_team: 5, away_team_goals: 1, in_progress: false },
  { id: 14, home_team: 14, home_team_goals: 2, away_team: 16, away_team_goals: 1, in_progress: false },
  { id: 15, home_team: 10, home_team_goals: 0, away_team: 15, away_team_goals: 1, in_progress: false },
  { id: 16, home_team: 11, home_team_goals: 0, away_team: 7, away_team_goals: 0, in_progress: false },
  { id: 17, home_team: 1, home_team_goals: 2, away_team: 8, away_team_goals: 3, in_progress: false },
  { id: 18, home_team: 12, home_team_goals: 4, away_team: 5, away_team_goals: 2, in_progress: false },
  { id: 19, home_team: 11, home_team_goals: 2, away_team: 2, away_team_goals: 2, in_progress: false },
  { id: 20, home_team: 7, home_team_goals: 0, away_team: 9, away_team_goals: 1, in_progress: false },
  { id: 21, home_team: 6, home_team_goals: 3, away_team: 13, away_team_goals: 1, in_progress: false },
  { id: 22, home_team: 4, home_team_goals: 3, away_team: 3, away_team_goals: 1, in_progress: false },
  { id: 23, home_team: 15, home_team_goals: 2, away_team: 16, away_team_goals: 3, in_progress: false },
  { id: 24, home_team: 10, home_team_goals: 2, away_team: 14, away_team_goals: 2, in_progress: false },
  { id: 25, home_team: 2, home_team_goals: 0, away_team: 6, away_team_goals: 1, in_progress: false },
  { id: 26, home_team: 13, home_team_goals: 1, away_team: 1, away_team_goals: 0, in_progress: false },
  { id: 27, home_team: 5, home_team_goals: 1, away_team: 15, away_team_goals: 2, in_progress: false },
  { id: 28, home_team: 16, home_team_goals: 3, away_team: 7, away_team_goals: 0, in_progress: false },
  { id: 29, home_team: 9, home_team_goals: 0, away_team: 4, away_team_goals: 4, in_progress: false },
  { id: 30, home_team: 3, home_team_goals: 0, away_team: 12, away_team_goals: 4, in_progress: false },
  { id: 31, home_team: 8, home_team_goals: 2, away_team: 10, away_team_goals: 0, in_progress: false },
  { id: 32, home_team: 14, home_team_goals: 5, away_team: 11, away_team_goals: 1, in_progress: false },
  { id: 33, home_team: 1, home_team_goals: 1, away_team: 16, away_team_goals: 1, in_progress: false },
  { id: 34, home_team: 9, home_team_goals: 3, away_team: 6, away_team_goals: 1, in_progress: false },
  { id: 35, home_team: 10, home_team_goals: 1, away_team: 5, away_team_goals: 3, in_progress: false },
  { id: 36, home_team: 2, home_team_goals: 0, away_team: 7, away_team_goals: 1, in_progress: false },
  { id: 37, home_team: 15, home_team_goals: 0, away_team: 13, away_team_goals: 1, in_progress: false },
  { id: 38, home_team: 14, home_team_goals: 2, away_team: 4, away_team_goals: 1, in_progress: false },
  { id: 39, home_team: 3, home_team_goals: 2, away_team: 11, away_team_goals: 0, in_progress: false },
  { id: 40, home_team: 12, home_team_goals: 4, away_team: 8, away_team_goals: 1, in_progress: false },
  { id: 41, home_team: 16, home_team_goals: 2, away_team: 9, away_team_goals: 0, in_progress: true },
  { id: 42, home_team: 6, home_team_goals: 1, away_team: 1, away_team_goals: 0, in_progress: true },
  { id: 43, home_team: 11, home_team_goals: 0, away_team: 10, away_team_goals: 0, in_progress: true },
  { id: 44, home_team: 7, home_team_goals: 2, away_team: 15, away_team_goals: 2, in_progress: true },
  { id: 45, home_team: 5, home_team_goals: 1, away_team: 3, away_team_goals: 1, in_progress: true },
  { id: 46, home_team: 4, home_team_goals: 1, away_team: 12, away_team_goals: 1, in_progress: true },
  { id: 47, home_team: 8, home_team_goals: 1, away_team: 14, away_team_goals: 2, in_progress: true },
  { id: 48, home_team: 13, home_team_goals: 1, away_team: 2, away_team_goals: 1, in_progress: true }
];
